name: "Maven Spring Boot Tests"
description: "Runs spring boot tests using maven"

inputs:
  aws-region:
    required: true
    description: "The aws-region used to authenticate with AWS"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'maven'
    - run: mvn clean test -DAWS_REGION=${{ inputs.aws-region }}
      shell: bash
