name: "Deploy to ECS"
description: "Builds and deploys the React frontend to AWS S3"
inputs:
  aws-access-key-id:
    required: true
    description: "The aws-access-key-id used to authenticate with AWS"
  aws-secret-access-key:
    required: true
    description: "The aws-secret-access-key used to authenticate with AWS"
  aws-region:
    required: true
    description: "The aws-region used to authenticate with AWS"
  ecr-image:
    required: true
    description: "The ecr-image of the service to be deployed"

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        # Actions cannot access secrets so pass them in as inputs
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - id: deploy-ecs-service
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ env.ENVIRONMENT }}-reward-service
        template: stacks/ecs-service.yaml
        no-fail-on-empty-changeset: "1"
        capabilities: 'CAPABILITY_IAM, CAPABILITY_NAMED_IAM' # CAPABILITY_AUTO_EXPAND required by lambda, CAPABILITY_IAM - default, CAPABILITY_NAMED_IAM - by task role
        parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}, ImageUrl=${{ inputs.ecr-image }}"