spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rewards
    username: myuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  boot:
    admin:
      client:
        url: http://localhost:8080/api/admin
server:
  port: ${random.int(9999)}