server:
  port: ${CONTAINER_PORT:8080}
  servlet:
    context-path: /api/reward
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: ${ACTIVE_ENVIRONMENT:local}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jdbc-interceptors: com.amazonaws.xray.sql.postgres.TracingInterceptor
  jpa:
    hibernate:
      ddl-auto: validate
security:
  oauth2:
    resource:
      userInfoUri: https://${COGNITO_APPLICATION_DOMAIN_NAME}.auth.${COGNITO_REGION}.amazoncognito.com/oauth2/userInfo
      tokenInfoUri: https://${COGNITO_APPLICATION_DOMAIN_NAME}.auth.${COGNITO_REGION}.amazoncognito.com/oauth2/token
      jwk:
        key-set-uri: https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
    client:
      clientId: ${COGNITO_CLIENT_ID}
management:
  endpoints:
    web:
      exposure:
        include: "*"