server:
  port: ${CONTAINER_PORT:8080}
  servlet:
    context-path: /api/reward
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: ${ACTIVE_ENVIRONMENT:local}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
          issuer-uri: https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
management:
  tracing:
    sampling:
      probability: 0.0
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    io.awspring.cloud: TRACE
service:
  listener:
    sqs:
      reward: ${GIFT_LIFECYCLE_QUEUE:gift-lifecycle}