name: Development - Deploy to Amazon ECS

on:
  push:
    branches:
      - develop
      - feature/*

env:
  ENVIRONMENT: development                   # set this to your preferred AWS region, e.g. us-west-1
  AWS_REGION: eu-central-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: reward                     # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                              # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                              # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  run-tests:
    name: Tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build-image:
    name: Build and Publish Image
    needs: run-tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/aws-ecr-publish-image
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

  deploy-production:
    name: Deploy
    needs: build-image
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/aws-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
