name: Development - Deploy to Amazon ECS

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: development               # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: reward                 # set this to your Amazon ECR repository name
  AWS_REGION: ${{ secrets.AWS_REGION }}  # set this to your Amazon ECR repository name

permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

  run-tests:
    name: Tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mvn-spring-boot-tests
        with:
          aws-region: ${{ secrets.AWS_REGION }}

  build-image:
    name: Build and Publish Image
    needs: run-tests
    environment: development
    runs-on: ubuntu-latest
    outputs:
      ecr-image: ${{ steps.set-ecr-image.outputs.ecr-image }}
      ecrimage1: ${{ steps.set-ecr-image.outputs.ecr-image }}
      ecrimage2: ${{ steps.aws-ecr-publish-image.outputs.ecr-image }}
    steps:
      - uses: actions/checkout@v3
      - id: aws-ecr-publish-image
        uses: ./.github/actions/aws-ecr-publish-image
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - id: set-ecr-image
        run: |
          echo "build-image step results"
          echo "ecr-image - ${{ steps.aws-ecr-publish-image.outputs.ecr-image }}"
          echo "ecr-image=${{ steps.aws-ecr-publish-image.outputs.ecr-image }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy
    needs: build-image
    environment: development
    runs-on: ubuntu-latest
    steps:
      - env:
          ECR_IMAGE: ${{ needs.build-image.outputs.ecr-image }}
        run: |
          echo "ECR_IMAGE - $ECR_IMAGE"
          echo "GITHUB_OUTPUT - $GITHUB_OUTPUT"
          echo "needs.build-image.outputs.ecr-image - ${{ needs.build-image.outputs.ecr-image }}"
          echo "needs.build-image.outputs.ecrimage1 - ${{ needs.build-image.outputs.ecrimage1 }}"
          echo "needs.build-image.outputs.ecrimage2 - ${{ needs.build-image.outputs.ecrimage2 }}"
          echo "needs.build-image.outputs - ${{ needs.build-image.outputs }}"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/aws-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          ecr-image: ${{ needs.build-image.outputs.ecr-image }}