name: Development - Deploy to Amazon ECS

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: development               # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: reward                 # set this to your Amazon ECR repository name
  AWS_REGION: ${{ secrets.AWS_REGION }}  # set this to your Amazon ECR repository name

permissions:
  contents: read

jobs:
  run-tests:
    name: Tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mvn-spring-boot-tests
        with:
          aws-region: ${{ secrets.AWS_REGION }}

  build-image-and-deploy:
    name: Build image and deploy ECS
    needs: run-tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: aws-ecr-publish-image
        name: Build and publish to ECR
        uses: ./.github/actions/aws-ecr-publish-image
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy ECS
        uses: ./.github/actions/aws-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          ecr-image: ${{ steps.aws-ecr-publish-image.outputs.ecr-image }}