name: Production - Deploy to Amazon ECS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1                      # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: reward                     # set this to your Amazon ECR repository name

permissions:
  contents: read

jobs:
  deploy-production:
    name: Deploy production
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/aws-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
