name: Development - Deploy to Amazon ECS

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: development               # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: reward                 # set this to your Amazon ECR repository name
  AWS_REGION: ${{ secrets.AWS_REGION }}  # set this to your Amazon ECR repository name

permissions:
  contents: read

jobs:
  run-tests:
    name: Tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mvn-spring-boot-tests
        with:
          aws-region: ${{ secrets.AWS_REGION }}

  build-image:
    name: Build and Publish Image
    needs: run-tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/aws-ecr-publish-image
        id: aws-ecr-publish-image
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          echo "outputs=${{ steps.aws-ecr-publish-image.outputs.ecr-image }}"
    outputs:
      ecr-image: ${{ steps.aws-ecr-publish-image.outputs.ecr-image }}

  deploy:
    name: Deploy
    needs: build-image
    environment: development
    runs-on: ubuntu-latest
    env:
      ECR_IMAGE: ${{ needs.build-image.outputs.ecr-image }}
    steps:
      - run: |
          echo "outputs=${{ needs.build-image.outputs.ecr-image }}"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/aws-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          ecr-image: ${{ env.ECR_IMAGE }}