name: Development - Deploy to Amazon ECS

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: development               # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: reward                 # set this to your Amazon ECR repository name
  AWS_REGION: ${{ secrets.AWS_REGION }}  # set this to your Amazon ECR repository name

permissions:
  contents: read

jobs:
  run-tests:
    name: Tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mvn-spring-boot-tests
        with:
          aws-region: ${{ secrets.AWS_REGION }}

  build-image:
    name: Build and Publish Image
    needs: run-tests
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/aws-ecr-publish-image
        id: aws-ecr-publish-image
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          echo "build-image step results"
          echo "ecr-image - ${{ steps.aws-ecr-publish-image.outputs.ecr-image }}"
          echo "ecr-image=${{ steps.aws-ecr-publish-image.outputs.ecr-image }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy
    needs: build-image
    environment: development
    runs-on: ubuntu-latest
    steps:
      - env:
          ECR_IMAGE: ${{ needs.build-image.outputs.ecr-image }}
        run: |
          echo "ECR_IMAGE - $ECR_IMAGE"
          echo "GITHUB_OUTPUT - $GITHUB_OUTPUT"
          echo "needs.build-image.outputs.ecr-image - ${{ needs.build-image.outputs.ecr-image }}"
          echo "needs.build-image.outputs - ${{ needs.build-image.outputs }}"
      - uses: actions/checkout@v3
      - env:
          ECR_IMAGE: ${{ needs.build-image.outputs.ecr-image }}
        uses: ./.github/actions/aws-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          ecr-image: ${{ env.ECR_IMAGE }}